### ISSUE TITLE
Rails 5 / Invalid option --profile

### ISSUE THREAD

**Issue by fighterii** [lemurheavy/coveralls-ruby#101]
I don't know if thats really an issue, but i can't find any workaround and it definitely comes from coveralls.

In our project we set up Coveralls to merge the results from cucumber and spec. 

As described on the page we used this code within the Rakefile:

```
require 'coveralls/rake/task'
Coveralls::RakeTask.new
task :test_with_coveralls => [:spec, :cucumber, 'coveralls:push']
```

When `test_with_coveralls` is executed, i can see in the command line, that the following command is executed for cucumber:

`/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby -S bundle exec cucumber --profile default`

which then leads to the following error:
```
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-5.0.0/lib/rails/test_unit/minitest_plugin.rb:57:in `plugin_rails_options': invalid option: --profile (OptionParser::InvalidOption)
        from /usr/local/rvm/gems/ruby-2.3.0/gems/minitest-5.9.0/lib/minitest.rb:200:in `block (2 levels) in process_args'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/minitest-5.9.0/lib/minitest.rb:198:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/minitest-5.9.0/lib/minitest.rb:198:in `block in process_args'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/minitest-5.9.0/lib/minitest.rb:168:in `new'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/minitest-5.9.0/lib/minitest.rb:168:in `process_args'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/minitest-5.9.0/lib/minitest.rb:122:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/minitest-5.9.0/lib/minitest.rb:62:in `block in autorun'
```

As far as i can recall, this only happens after our upgrade to Rails-5 (which may has to do with railties-5.0.0).

But somehow Coveralls adds this `--profile default` option to the end of the task, which causes this error.
Does anyone know how to avoid this?

**Comment by fighterii** [comment]
This can be specified in the `lib/tasks/cucumber.rake` file
