### ISSUE TITLE
Simplecov error when using merged results

### ISSUE THREAD

**Issue by thomas-mcdonald** [lemurheavy/coveralls-ruby#12]
I'm trying to set merge support up with one of my repositories, but (I assume) [setting the formatter to nil](https://github.com/lemurheavy/coveralls-ruby/commit/844c0c78b4f31695e4f3c74ca8c761a9321fc7e0#L1R21) is causing an error after cucumber has been run.

```
/Users/tom/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/simplecov-0.7.1/lib/simplecov/result.rb:91:in `format!': undefined method `new' for nil:NilClass (NoMethodError)
  from /Users/tom/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/simplecov-0.7.1/lib/simplecov/configuration.rb:133:in `block in at_exit'
    from /Users/tom/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/simplecov-0.7.1/lib/simplecov/defaults.rb:52:in `call'
    from /Users/tom/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/simplecov-0.7.1/lib/simplecov/defaults.rb:52:in `block in <top (required)>'
rake aborted!
```

At the top of both `features/env.rb` and `spec/spec_helper.rb` I have the coveralls load lines:

``` ruby
require 'coveralls'
Coveralls.wear_merged!('rails')
```

This is the rake task I am using, although I imagine that this is somewhat irrelevant:

``` ruby
require 'coveralls/rake/task'
Coveralls::RakeTask.new

namespace :ci do
  desc "Run tests on Travis."
  task :travis do
    puts "Starting to run cucumber..."
    system("bundle exec rake cucumber")
    raise "Cucumber failed!" unless $?.exitstatus == 0

    puts "Starting to run rspec..."
    system("export RSPEC=true && bundle exec rake spec")
    raise "RSpec failed!" unless $?.exitstatus == 0

    Rake::Task["coveralls:push"].invoke
  end
end

task travis: "ci:travis"
```

**Comment by mathieujobin** [comment]
is this fixed ? 
3 years later, I am still having problems with coveralls merging rspec&&cucumber results
