### ISSUE TITLE
Undefined method `<<' for Hash when Submitting to https://coveralls.io/api/v1

### ISSUE THREAD

**Issue by daninfpj** [lemurheavy/coveralls-ruby#141]
I‘m sending coverage results from CircleCI, and it worked for a while. Not sure what changed, but I’m now getting this error:

```
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
....

Finished in 0.02172 seconds (files took 1.53 seconds to load)
4 examples, 0 failures

[Coveralls] Submitting to https://coveralls.io/api/v1
Coveralls encountered an exception:
NoMethodError
undefined method `<<' for {:read_timeout=>60, :continue_timeout=>nil, :debug_output=>nil}:Hash
Did you mean?  <
/usr/local/lib/ruby/2.4.0/net/protocol.rb:219:in `writing'
/usr/local/lib/ruby/2.4.0/net/protocol.rb:202:in `write'
/usr/local/lib/ruby/2.4.0/net/http/generic_request.rb:334:in `write_header'
/usr/local/lib/ruby/2.4.0/net/http/generic_request.rb:186:in `send_request_with_body'
/usr/local/lib/ruby/2.4.0/net/http/generic_request.rb:121:in `exec'
/usr/local/lib/ruby/2.4.0/net/http.rb:1444:in `block in transport_request'
/usr/local/lib/ruby/2.4.0/net/http.rb:1443:in `catch'
/usr/local/lib/ruby/2.4.0/net/http.rb:1443:in `transport_request'
/usr/local/lib/ruby/2.4.0/net/http.rb:1416:in `request'
/home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/webmock-1.24.6/lib/webmock/http_lib_adapters/net_http.rb:97:in `block in request'
/home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/webmock-1.24.6/lib/webmock/http_lib_adapters/net_http.rb:110:in `block in request'
/usr/local/lib/ruby/2.4.0/net/http.rb:877:in `start'
/home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/webmock-1.24.6/lib/webmock/http_lib_adapters/net_http.rb:109:in `request'
/home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/coveralls-0.8.22/lib/coveralls/api.rb:29:in `post_json'
/home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/coveralls-0.8.22/lib/coveralls/simplecov.rb:64:in `format'
/home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/simplecov-0.16.1/lib/simplecov/result.rb:48:in `format!'
/home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/simplecov-0.16.1/lib/simplecov/configuration.rb:182:in `block in at_exit'
/home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/simplecov-0.16.1/lib/simplecov.rb:200:in `run_exit_tasks!'
/home/circleci/repo/vendor/bundle/ruby/2.4.0/gems/simplecov-0.16.1/lib/simplecov/defaults.rb:27:in `block in <top (required)>'
```

Any ideas?

**Comment by fernandoaleman** [comment]
@daninfpj Did you ever get this resolved? If so, what was the solution? I am running into this with an old app now.

**Comment by daninfpj** [comment]
> @daninfpj Did you ever get this resolved? If so, what was the solution? I am running into this with an old app now.

@fernandoaleman I never did, I just gave up. The project I was using it in is also stale so it didn’t matter anymore.

**Comment by fernandoaleman** [comment]
> @fernandoaleman I never did, I just gave up. The project I was using it in is also stale so it didn’t matter anymore.

@daninfpj Oh okay. Thanks for the quick response. 👍

**Comment by nikgregory** [comment]
This is an issue with webmock 1.24.6 (and prehaps others). I ran into this issue when updating a ruby gem I maintain and had to update webmock.  Being aggressive, I just updated to the latest version.

**Comment by fernandoaleman** [comment]
> This is an issue with webmock 1.24.6 (and prehaps others). I ran into this issue when updating a ruby gem I maintain and had to update webmock. Being aggressive, I just updated to the latest version.

@nikgregory THIS WORKED! You are a gentleman and a scholar. Not sure why I didn't think of upgrading that gem, but it's all working now. Thanks so much. Saved me a TON of time! 👍
