### ISSUE TITLE
undefined method `coverage' for #<SimpleCov::SourceFile>

### ISSUE THREAD

**Issue by janosrusiczki** [lemurheavy/coveralls-ruby#161]
I'm logging this bug as well as a solution for anyone who encounters this.

I ran a bundle update and I've been getting the following error when my CI system tried to send the coverage results to Coveralls:

```
Coveralls encountered an exception:

NoMethodError
undefined method `coverage' for #<SimpleCov::SourceFile:0x000000000cb4b610>
Did you mean?  coverage_data

/home/travis/build/haiafara/haiafara-ro/vendor/bundle/ruby/2.6.0/gems/coveralls-0.7.1/lib/coveralls/simplecov.rb:50:in `block in format'
/home/travis/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/travis/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/home/travis/build/haiafara/haiafara-ro/vendor/bundle/ruby/2.6.0/gems/coveralls-0.7.1/lib/coveralls/simplecov.rb:40:in `format'
/home/travis/build/haiafara/haiafara-ro/vendor/bundle/ruby/2.6.0/gems/simplecov-0.18.5/lib/simplecov/result.rb:49:in `format!'
/home/travis/build/haiafara/haiafara-ro/vendor/bundle/ruby/2.6.0/gems/simplecov-0.18.5/lib/simplecov/configuration.rb:196:in `block in at_exit'
/home/travis/build/haiafara/haiafara-ro/vendor/bundle/ruby/2.6.0/gems/simplecov-0.18.5/lib/simplecov.rb:214:in `run_exit_tasks!'
/home/travis/build/haiafara/haiafara-ro/vendor/bundle/ruby/2.6.0/gems/simplecov-0.18.5/lib/simplecov.rb:202:in `at_exit_behavior'
/home/travis/build/haiafara/haiafara-ro/vendor/bundle/ruby/2.6.0/gems/simplecov-0.18.5/lib/simplecov/defaults.rb:27:in `block in <top (required)>'
```

This is because it seems simplecov 0.18 dropped the coverage property from their `SourceFile` object.

**Comment by janosrusiczki** [comment]
The solution was to switch to [tagliala/coveralls-ruby-reborn](https://github.com/tagliala/coveralls-ruby-reborn) which is a well maintained gem, as opposed to this.

For those curious the fix was here: https://github.com/tagliala/coveralls-ruby-reborn/commit/46b2949e0e79b936e640146076f95ead0d322fad#diff-07e218a680913917fbacbf63ea2056e2R47

Thanks for this issue's thread: https://github.com/lemurheavy/coveralls-ruby/issues/130

**Comment by stevebissett** [comment]
I have this same issue.
