### ISSUE TITLE
Test failures with Ruby 3.1

### ISSUE THREAD

**Issue by voxik** [lemurheavy/coveralls-ruby#173]
With Ruby 3.1 landing in Fedora, there appears to be one test failure in Coveralls:

~~~
$ rspec -Ilib --tag '~if' spec

... snip ...

.........
An error occurred in an `after(:context)` hook.
Failure/Error:
  SimpleCov.start do
    add_filter do |source_file|
      source_file.filename =~ /spec/ && !(source_file.filename =~ /fixture/)
    end
  end
RuntimeError:
  coverage measurement is already setup
# /usr/share/gems/gems/simplecov-0.13.0/lib/simplecov.rb:48:in `start'
# /usr/share/gems/gems/simplecov-0.13.0/lib/simplecov.rb:48:in `start'
# ./spec/spec_helper.rb:21:in `setup_formatter'
# ./spec/coveralls/coveralls_spec.rb:104:in `block (2 levels) in <top (required)>'
...............
Finished in 0.32023 seconds (files took 0.93759 seconds to load)
44 examples, 0 failures, 1 error occurred outside of examples
~~~

While I we have quite old version of Coveralls, checking the upstream repository, `coveralls_spec.rb` neither `spec_helper.rb` were modified recently.

However, checking Ruby, there is one change in Ruby 3.1 which seems to be related:

https://github.com/ruby/ruby/commit/86e3d77abb8a033650937710d1ab009e98647494

**Comment by mathieujobin** [comment]
have you tried switching to https://github.com/tagliala/coveralls-ruby-reborn ?
