### ISSUE TITLE
JSON output errors

### ISSUE THREAD

**Issue by olivierlacan** [lemurheavy/coveralls-ruby#19]
Any idea why I'm getting this stuff at the end of a test run? Happens only in Development.

```
/Users/username/Development/dir/.bundle/gems/json-1.7.7/lib/json/common.rb:155:in `parse': 795: unexpected token at 'null, (MultiJson::LoadError)
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        0,
        null,
        0,
        null,
        null,
        null,
        1,
        1,
        null,
        1,
        null,
        null,
        1,
        1,
        1,
        1,
        null,
        1,
        1,
        1,
        null,
        null,
        1,
        1,
        1,
        null,
        null,
        null,
        1,
        1,
        1,
        null,
        1,
        0,
        0,
        0,
        0,
        null,
        null,
        null,
        1,
        1,
        1,
        null,
        1,
        1,
        null,
        null,
        1,
        1,
        1,
        null,
        null,
        1,
        1,
        1,
        1,
        null,
        null,
        null,
        1,
        1,
        0,
        0,
        0,
        null,
        null,
        null,
        1,
        null,
        0,
        null,
        null,
        null,
        1,
        1,
        0,
        0,
        0,
        null,
        null,
        null,
        1,
        null,
        0,
        null,
        null,
        null,
        1,
        1,
        null,
        0,
        null,
        null,
        1,
        null,
        0,
        null,
        null,
        null,
        1,
        1,
        null,
        0,
        null,
        null,
        1,
        null,
        0,
        null,
        null,
        1,
        0,
        null,
        0,
        null,
        null,
        null,
        1,
        1,
        0,
        0,
        0,
        null,
        null,
        null,
        1,
        1,
        0,
        null,
        null,
        1,
        0,
        0,
        0,
        null,
        null,
        null,
        null,
        1,
        1,
        1,
        null,
        1,
        1,
        1,
        null,
        null,
        1,
        1,
        null,
        1,
        null,
        null,
        1,
        1,
        null,
        1,
        null,
        1,
        0,
        null,
        null,
        null,
        1,
        1,
        null,
        1,
        1,
        null,
        null,
        1,
        1,
        1,
        1,
        null,
        1,
        null,
        1,
        null,
        1,
        0,
        0,
        null,
        null,
        null,
        null,
        1,
        1,
        1,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        null,
        1,
        1,
        null,
        1,
        0,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        null,
        null,
        1,
        1,
        1,
        0,
        0,
        null,
        null,
        null,
        null,
        null,
        1,
        null,
        1,
        0,
        0,
        null,
        null,
        1,
        1,
        1,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        1,
        null,
        1,
        0,
        0,
        0,
        null,
        null,
        1,
        0,
        null,
        0,
        0,
        0,
        0,
        null,
        null,
        null,
        null,
        1,
        1,
        1,
        null,
        1,
        0,
        null,
        null,
        null,
        null,
        1,
        1,
        1,
        1,
        null,
        1,
        0,
        null,
        null,
        null,
        1,
        1,
        1,
        null,
        1,
        0,
        null,
        null,
        null,
        null,
        1,
        1,
        1,
        null,
        1,
        1,
        null,
        1,
        0,
        0,
        null,
        null,
        1,
        0,
        0,
        null,
        null,
        1,
        0,
        0,
        null,
        null,
        null,
        null,
        1,
        1,
        null,
        1,
        1,
        1,
        null,
        1,
        0,
        null,
        0,
        null,
        null,
        null,
        1,
        1,
        null,
        1,
        1,
        null,
        1,
        0,
        0,
        null,
        null,
        null,
        1,
        1,
        null,
        1,
        1,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        0,
        0,
        null,
        null,
        null,
        1,
        1,
        null,
        1,
        1,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        0,
        0,
        null,
        null,
        null,
        null
      ],
      "/Users/username/Development/dir/spec/requests/client_authentication_spec.rb": [
        null,
        1,
        null,
        1,
        1,
        1,
        null,
        1,
        1,
        1,
        1,
        1,
        null,
        1,
        null,
        null,
        null,
        null,
        0,
        0,
        null,
        0,
        0,
        null,
        null,
        null,
        1,
        null,
        1,
        1,
        0,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        null,
        1,
        1,
        0,
        0,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        null,
        null,
        null
      ],
      "/Users/username/Development/dir/spec/services/course_access_policy/policy_spec.rb": [
        1,
        null,
        1,
        1,
        1,
        1,
        1,
        1,
        null,
        1,
        1,
        1,
        0,
        null,
        null,
        1,
        null,
        null,
        1,
        1,
        0,
        null,
        null,
        1,
        null,
        null,
        null,
        null
      ],
      "/Users/username/Development/dir/.bundle/gems/database_cleaner-0.9.1/lib/database_cleaner/active_record/transaction.rb": [
        1,
        1,
        null,
        1,
        1,
        1,
        1,
        null,
        1,
        0,
        0,
        null,
        0,
        null,
        0,
        null,
        null,
        null,
        1,
        0,
        null,
        0,
        null,
        0,
        0,
        null,
        0,
        null,
        null,
        null,
        null
      ],
      "/Users/username/Development/dir/.bundle/gems/database_cleaner-0.9.1/lib/database_cleaner/active_record/base.rb": [
        1,
        1,
        1,
        null,
        1,
        1,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        1,
        null,
        1,
        null,
        1,
        3,
        3,
        null,
        null,
        1,
        3,
        null,
        null,
        1,
        3,
        0,
        0,
        null,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        null,
        1,
        null,
        0,
        null,
        0,
        1,
        null,
        null,
        1,
        null,
        1,
        0,
        0,
        0,
        0,
        null,
        null,
        null,
        1,
        0,
        0,
        0,
        null,
        null,
        null,
        null,
        null
      ],
      "/Users/username/Development/dir/.bundle/gems/database_cleaner-0.9.1/lib/database_cleaner/generic/base.rb": [
        1,
        1,
        1,
        null,
        1,
        1,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        1,
        0,
        null,
        null,
        null,
        null,
        null
      ],
      "/Users/username/Development/dir/.bundle/gems/database_cleaner-0.9.1/lib/database_cleaner/generic/transaction.rb": [
        1,
        1,
        1,
        1,
        3,
        0,
        null,
        null,
        null,
        null,
        null
      ],
      "/Users/username/Development/dir/.bundle/gems/database_cleaner-0.9.1/lib/database_cleaner/active_record/truncation.rb": [
        1,
        null,
        1,
        null,
        1,
        1,
        null,
        null,
        null,
        1,
        1,
        null,
        1,
        1,
        null,
        1,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        null,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        0,
        null,
        null,
        null,
        null,
        1,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        0,
        null,
        null,
        1,
        null,
        null,
        1,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        0,
        0,
        null,
        null,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        1,
        0,
        null,
        null,
        null,
        null,
        1,
        1,
        0,
        null,
        null,
        null,
        null,
        1,
        1,
        0,
        0,
        null,
        1,
        null,
        null,
        1,
        1,
        0,
        0,
        0,
        0,
        null,
        null,
        null,
        null,
        1,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        0,
        null,
        null,
        1,
        0,
        0,
        null,
        null,
        1,
        null,
        null,
        null,
        null,
        null,
        1,
        0,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        null,
        1,
        1,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        1,
        null,
        1,
        null,
        1,
        1,
        null,
        null,
        1,
        1,
        null,
        null,
        null,
        null,
        1,
        0,
        0,
        null,
        1,
        1,
        null,
        null,
        1,
        1,
        null,
        1,
        1,
        null,
        null,
        1,
        1,
        null,
        null,
        1,
        1,
        null,
        null,
        1,
        1,
        null,
        null,
        1,
        1,
        null,
        null,
        1,
        1,
        null,
        null,
        1,
        1,
        null,
        null,
        1,
        1,
        null,
        null,
        null,
        null,
        null,
        null,
        1,
        1,
        1,
        1,
        null,
        1,
        1,
        0,
        0,
        0,
        null,
        0,
        null,
        null,
        null,
        null,
        1,
        null,
        1,
        0,
        null,
        null,
        null,
        1,
        1,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        0,
        null,
        null,
        null
      ],
      "/Users/username/Development/dir/.bundle/gems/database_cleaner-0.9.1/lib/database_cleaner/generic/truncation.rb": [
        1,
        1,
        1,
        1,
        1,
        0,
        null,
        1,
        0,
        null,
        null,
        1,
        1,
        1,
        1,
        1,
        null,
        null,
        1,
        null,
        null,
        null,
        1,
        0,
        null,
        null,
        1,
        1,
        0,
        null,
        null,
        null,
        null,
        1,
        0,
        null,
        null,
        null,
        null
      ]
    },
    "timestamp": 1365989087
  }
}
'
  from /Users/username/Development/dir/.bundle/gems/json-1.7.7/lib/json/common.rb:155:in `parse'
  from /Users/username/Development/dir/.bundle/gems/multi_json-1.7.2/lib/multi_json/adapters/json_common.rb:16:in `load'
  from /Users/username/Development/dir/.bundle/gems/multi_json-1.7.2/lib/multi_json/adapter.rb:19:in `load'
  from /Users/username/Development/dir/.bundle/gems/multi_json-1.7.2/lib/multi_json.rb:120:in `load'
  from /Users/username/Development/dir/.bundle/gems/simplecov-0.7.1/lib/simplecov/json.rb:8:in `parse'
  from /Users/username/Development/dir/.bundle/gems/simplecov-0.7.1/lib/simplecov/result_merger.rb:16:in `resultset'
  from /Users/username/Development/dir/.bundle/gems/simplecov-0.7.1/lib/simplecov/result_merger.rb:65:in `store_result'
  from /Users/username/Development/dir/.bundle/gems/simplecov-0.7.1/lib/simplecov.rb:48:in `result'
  from /Users/username/Development/dir/.bundle/gems/simplecov-0.7.1/lib/simplecov/configuration.rb:133:in `block in at_exit'
  from /Users/username/Development/dir/.bundle/gems/simplecov-0.7.1/lib/simplecov/defaults.rb:52:in `call'
  from /Users/username/Development/dir/.bundle/gems/simplecov-0.7.1/lib/simplecov/defaults.rb:52:in `block in <top (required)>'
```

**Comment by kbrock** [comment]
@olivierlacan is this still a problem?

**Comment by olivierlacan** [comment]
@kbrock I don't use this gem anymore, couldn't tell you. Sorry. I'll close for now.
